### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by QuantumCyberW0lf** [gyoisamurai/GyoiThon#3] opened 2018-03-23 13:25 UTC
Here are the errors what I got:

    Exception: [Errno 2] No such file or directory: '/home/github/GyoiThon/signatures/signature_framework.txt'
    [*] Exception: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:833)>

    Traceback (most recent call last):
    File "gyoithon.py", line 228, in
    products = classifier.analyzer(ip_list[idx], int(port_list[idx]), ip_list[idx])
    File "./classifier4gyoithon/GyoiClassifier.py", line 95, in analyzer
    fin = codecs.open(logfile_path, 'r', encoding='utf-8')
    File "/usr/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/github/GyoiThon/classifier4gyoithon/../http://192.168.2.110:80'

**Comment by gyoisamurai** [comment] 2018-03-26 06:15
@QuantumCyberW0lf Please check following.  
```
Exception: [Errno 2] No such file or directory: '/home/github/GyoiThon/signatures/signature_framework.txt'
[*] Exception: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:833)>
```
It was caused by the absence of "signature_framework.txt". We uploaded a "signature_framework.txt".

```
Traceback (most recent call last):
File "gyoithon.py", line 228, in
products = classifier.analyzer(ip_list[idx], int(port_list[idx]), ip_list[idx])
File "./classifier4gyoithon/GyoiClassifier.py", line 95, in analyzer
fin = codecs.open(logfile_path, 'r', encoding='utf-8')
File "/usr/lib/python3.6/codecs.py", line 897, in open
file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/home/github/GyoiThon/classifier4gyoithon/../http://192.168.2.110:80'
```
We fixed bug at GyoiClassifier.py.

**Comment by gyoisamurai** [comment] 2018-03-26 06:41
We close this issue.

**Closed by gyoisamurai** 2018-03-26 06:41 UTC
