### ISSUE TITLE
error when executing  python gyoithon.py

### ISSUE THREAD

**Issue by emans841** [gyoisamurai/GyoiThon#2] opened 2018-03-23 08:39 UTC
python gyoithon.py
Traceback (most recent call last):
  File "gyoithon.py", line 9, in <module>
    import pandas as pd
ImportError: No module named pandas

**Comment by ashr** [comment] 2018-03-23 10:49
You need to install the requirements bro, its in the readme

**Comment by emans841** [comment] 2018-03-23 11:19
after installing the requirement i still gets this error 

Traceback (most recent call last):
  File "gyoithon.py", line 10, in <module>
    from urllib.request import urlopen
ImportError: No module named request

**Comment by QuantumCyberW0lf** [comment] 2018-03-23 13:14
Here are the errors what I got: 

1) Exception: [Errno 2] No such file or directory: '/home/github/GyoiThon/signatures/signature_framework.txt'
[*] Exception: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:833)>


2) Traceback (most recent call last):
  File "gyoithon.py", line 228, in <module>
    products = classifier.analyzer(ip_list[idx], int(port_list[idx]), ip_list[idx])
  File "./classifier4gyoithon/GyoiClassifier.py", line 95, in analyzer
    fin = codecs.open(logfile_path, 'r', encoding='utf-8')
  File "/usr/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/home/github/GyoiThon/classifier4gyoithon/../http://192.168.2.110:80'

**Comment by QuantumCyberW0lf** [comment] 2018-03-23 13:24
@emans841 : you should run python3. the default python is python2.7 doesn't have the request module

**Comment by gyoisamurai** [comment] 2018-03-26 06:11
@QuantumCyberW0lf Thank for issues. We already repaired. Please check following.

1. It was caused by the absence of "signature_framework.txt". We uploaded a "signature_framework.txt".
2. We fix bug at GyoiClassifier.py.

**Comment by gyoisamurai** [comment] 2018-03-26 06:12
@ashr Thanks for your support.

**Comment by gyoisamurai** [comment] 2018-03-26 06:40
We close this issue.

**Closed by gyoisamurai** 2018-03-26 06:40 UTC
